
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankApp
    username: postgres
    password: nicat12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
